# railway.toml

# Serviço VShop.Web
[services.vshopweb.build]
builder = "dockerfile"
dockerfilePath = "./VShop.Web/Dockerfile"

[services.vshopweb.deploy]
startCommand = "./VShop.Web"
restartPolicyType = "always"
healthcheckPath = "./VShop.Web//health"

# Serviço VShop.IdentityServer
[services.identityserver.build]
builder = "dockerfile"
dockerfilePath = "./VShop.IdentityServer/Dockerfile"

[services.identityserver.deploy]
startCommand = "./VShop.IdentityServer"
restartPolicyType = "always"
healthcheckPath = "./VShop.IdentityServer//health"

# Serviço VShop.DiscountApi
[services.discountapi.build]
builder = "dockerfile"
dockerfilePath = "./VShop.DiscountApi/Dockerfile"

[services.discountapi.deploy]
startCommand = "./VShop.DiscountApi"
restartPolicyType = "always"
healthcheckPath = "./VShop.DiscountApi//health"

# Serviço VShop.CartApi
[services.cartapi.build]
builder = "dockerfile"
dockerfilePath = "./VShop.CartApi/Dockerfile"

[services.cartapi.deploy]
startCommand = "./VShop.CartApi"
restartPolicyType = "always"
healthcheckPath = "./VShop.CartApi//health"

# Serviço VShop.Products
[services.products.build]
builder = "dockerfile"
dockerfilePath = "./VShop.Products/Dockerfile"

[services.products.deploy]
startCommand = "./VShop.Products"
restartPolicyType = "always"
healthcheckPath = "./VShop.Products//health"
